SYSEX_NON_REALTIME = 126
SYSEX_REALTIME = 127

SYSEX_NRT_IDENTITY_REQ = [6, 1]
SYSEX_NRT_IDENTITY_RES = [6, 2]


SYSEX_NAMES = {
    (6, 1): "IDENTITY_REQ",
    (6, 2): "IDENTITY_RES"
}

SYSEX_IDS = {item[1]: item[0] for item in SYSEX_NAMES}