FUNCTION_NAMES = {
    'LED_PALETTE': 10,
    'LED_RGB': 11,
    'COLUMN_PALETTE': 12,
    'ROW_PALETTE': 13,
    'ALL_PALETTE': 14,
    'SCROLL_TEXT': 20,
    'SCROLL_FINISHED': 21,
    'CHANGE_LAYOUT': 34,
    'FLASH_PALETTE': 35,
    'PULSE_PALETTE': 40,
    'FADER_SETUP': 43
}

FUNCTION_IDS = {key: value for value, key in FUNCTION_NAMES.items()}